[package]
name = "lcmh"
version = "0.1.0"
authors = ["Jannis Ruh <ruh.j81@gmail.com>"]

edition = "2024"
rust-version = "1.85.0" # first version for the 2024 edition

license = "MIT OR Apache-2.0"

repository = "https://github.com/taeruh/lcmh"

description = "# A Metropolis-Hastings MCMC Search on Local Complementations of a Graph"
keywords = ["graph", "local complementation", "metropolis-hastings"]
categories = ["mathematics", "science"]

readme = "README.md"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
